// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZp1K6dGvQ7GsjNtU-S-8Rt_kMbt5Ez-4',
    appId: '1:868649407040:android:af6b5b05f22182d49b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    storageBucket: 'mierp-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0ZWUGcKCJGonYSQanzPRhSAR9aTpqcs',
    appId: '1:868649407040:ios:454e67ef0c45ade79b05a5',
    messagingSenderId: '868649407040',
    projectId: 'mierp-apps',
    storageBucket: 'mierp-apps.firebasestorage.app',
    androidClientId: '868649407040-5drl6ti1gfgsb4sne1r8331piuhvq7jv.apps.googleusercontent.com',
    iosClientId: '868649407040-ul04ocjpdvp0kjamm9njlh8eb74tgs4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mierpApps',
  );

}